# Generated by Django 3.0 on 2020-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20200105_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='temp',
            field=models.CharField(default='nihao', max_length=200),
        ),
    ]
