# Generated by Django 3.0 on 2020-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='temp2',
            field=models.CharField(default='nihao', max_length=200),
        ),
    ]
